version: "3"
services:
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=klubu
      - POSTGRES_USER=klubu
      - POSTGRES_PASSWORD=klubu-test
      - POSTGRES_ROOT_PASSWORD=abc123testroot
    volumes:
      - klubu-data:/var/lib/postgresql/data:z

volumes:
  klubu-data:
